### ISSUE TITLE
how to use location data in page?

### ISSUE THREAD

**Issue by DevaLee** [icapps/flutter-background-location-tracker#74]

**Comment by ikbendewilliam** [comment]
What do you want to do? If you want to visualise the location of a user this Plugin is not the correct one, use geolocator instead :-). This plugin is for tracking in the background. 
If you want to visualise the tracked values, you need to save them in a database/sharedpreferences and load them in the UI from the same source. Be careful that you don't do it at the same time since that can cause issues.
